### ISSUE TITLE
Missing Louisville? 

### ISSUE THREAD

**Issue by evz** [censusreporter/census-api#24]
Just noticed that when one searches for Louisville, KY, one gets an error: http://censusreporter.org/profiles/16000US2148000-louisville-ky/

Digging a bit deeper, the ``/data/show/latest`` API endpoint returns a message saying: 

```json
{ 
    "error": "The ACS 2013 5-year release doesn't include GeoID(s) 16000US2148000." 
}
```
when one searches for data from that that GeoID.

**Comment by JoeGermuska** [comment]
This is a specific case of censusreporter/censusreporter#104. We're generally using that one repo for all issue tracking, so I'm going to close this one.

@evz as you and I discussed yesterday, the geoid 16000US2148000 is actually obsolete, as best I can tell. In fact, from the 2013 [geography notes](http://www.census.gov/acs/www/data_documentation/geography_notes/):
> **Changes to Louisville/Jefferson County Metro Government (Balance)**
In order to support specific federal program needs, in 2013 the Census Bureau's Geography Division created a new incorporated place record with a non-functioning status for the former Louisville city incorporated place extent. This reduced the extent of the previously existing Louisville/Jefferson county metro government (balance) incorporated place record, with the exclusion of the now current Louisville city incorporated place extent.
>
>ACS does not publish estimates for the unique Louisville city incorporated place extent. For the 2013 ACS estimates, in order to maintain consistency with the Census Bureau's Population Estimates Program and comparability over time, ACS retains the now former Louisville/Jefferson County metro government (balance) incorporated place geographic definition that includes the Louisville city incorporated place extent. This includes all estimates for summary level 160 (state-place), and all other ACS published summary levels with "place" in the description.

so... weird...
